# typings/mt5.pyi
from typing import Any, List, Optional, Tuple

class Error(Exception): ...

def initialize(
    path: str = ...,
    login: int = ...,
    password: str = ...,
    server: str = ...,
    timeout: int = ...,
    portable: bool = ...
) -> bool: ...

def shutdown() -> None: ...
def last_error() -> Tuple[int, str]: ...
def symbols_total() -> int: ...
def symbol_info(symbol: str) -> Any: ...
def symbol_info_tick(symbol: str) -> Any: ...
def positions_get(symbol: str = ...) -> List[Any]: ...
def order_send(request: dict) -> Any: ...
def copy_rates_from_pos(
    symbol: str,
    timeframe: int,
    start_pos: int,
    count: int
) -> Any: ...
def account_info() -> Any: ...